# Generated by Django 4.1.7 on 2023-03-26 10:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=100)),
                ('back', models.CharField(max_length=200)),
                ('ef', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='IMG')),
                ('last_review_date', models.DateTimeField(default=datetime.datetime.now)),
                ('next_review_date', models.DateTimeField(default=datetime.datetime.now)),
                ('deck_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Card.deck')),
            ],
        ),
    ]
